name: Validate Action Examples

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: read

jobs:
  validate-examples:
    uses: devops-actions/.github/.github/workflows/actions-example-checker.yml@a2dcba26c2b4e873ec3b9c6291ac680e2ea452a2 # main
    permissions:
      contents: read