name: Submit Actions Dependencies
on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1' # Weekly
jobs:
  submit-dependencies:
    uses: devops-actions/.github/.github/workflows/actions-dependencies.yml@a634e5b033926a6683519b3ffc7b556312ca7e00 # main
    permissions:
      contents: write # Required to read workflow files
      id-token: write # Required for dependency submission
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: read
