name: Validate Action Examples

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: read

jobs:
  validate-examples:
    uses: devops-actions/.github/.github/workflows/actions-example-checker.yml@3abe9f6710c33ede76f8a506b2889ee46a2c9646 # main
    permissions:
      contents: read