name: Validate Action Examples

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: read

jobs:
  validate-examples:
    uses: devops-actions/.github/.github/workflows/actions-example-checker.yml@36ef47f59df5b0ae9b4214ab664d18533abdb9bf # main
    permissions:
      contents: read